name: Unity Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4.0.1
        with:
          path: .${{ matrix.projectPath }}/testDevOps2
          key: testDevOps-${{ matrix.projectPath }}
          restore-keys: |
            testDevOps-
          
      - name: Test runner
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
