name: Unity Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          # Remove ".${{ matrix.projectPath }}"
          path: ${{ matrix.projectPath }}/testDevOps2  # Assuming testDevOps2 is the project folder within the checkout
          key: testDevOps-${{ matrix.projectPath }}
          restore-keys: |
            testDevOps-

     

      - name: Test runner (Optional)
        uses: game-ci/unity-test-runner@v4
        if: ${{ success() }}  # Run tests only if the build was successful (optional)
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
