name: List Root Directory Contents

on:
  push:
    branches:
      - main

jobs:
  list_contents:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: List Root Directory Contents
        run: ls -l .
