name: Unity Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

     
     - name: Checkout project
       uses: actions/checkout@v4

     - uses: game-ci/unity-test-runner@v4
       env:
         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
       with:
         projectPath: ./testDevOps2
         githubToken: ${{ secrets.GITHUB_TOKEN }}

     
