name: Unity Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

     
     - name: Checkout project
       uses: actions/checkout@v4

       env:
         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
       with:
         projectPath: ./testDevOps2
         githubToken: ${{ secrets.GITHUB_TOKEN }}

     - uses: game-ci/unity-builder@v4
       env:
         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       with:
         projectPath: ./testDevOps2
         targetPlatform: WebGL
